version: '2'
services:
  web:
    build: .
#    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./goat:/goat
      
#    environment:
#      - DJANGO_SETTINGS_MODULE=goat.settings.py

    ports:
      - "8000:8000"
