# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_item_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='Lista',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='list',
            new_name='lista',
        ),
    ]
