# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20170828_2353'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lista',
            new_name='List',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='lista',
            new_name='list',
        ),
    ]
